version: '3.5'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSQL_PID=Express
    ports:
      - "1433:1433"

volumes:
  sqldata: