/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.climb;

import java.util.Arrays;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        List<String> lista = Arrays.asList("a","b");
        System.out.println("Teste");
        lista.parallelStream().forEach(System.out::println);

        System.out.println(new App().getGreeting());
    }
}
